spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: ${spring.config.activate.on-profile}
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

---
spring:
  config:
    activate:
      on-profile: subject

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: verb

server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: object

server:
  port: 8083

---