server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      name: configserver
      server:
        git:
          uri:  https://github.com/Skeith94/Sentence-Generator
          username: Skeith94
          password: ${gitpassword}
          clone-on-start: true
          default-label: main

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
